name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - run: npm test
      - run: npm run build
  deploy:
    needs: [build_and_test]
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  notify_success:
    needs: [deploy]
    if: ${{ always() && needs.deploy.result == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Discord success
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: "Success"
          title: "Deployment Successful!"
          nodetail: true
          color: 0x00ff00
          description: |
            **Deployment Details**
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.user }}
  notify_failure:
    needs: [deploy, build_and_test]
    if: ${{ always() && (needs.build_and_test.result == 'failure' || needs.deploy.result == 'failure')}}
    runs-on: ubuntu-latest
    steps:
      - name: Discord failure
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: "Failure"
          title: "Build Failed!"
          color: 0xff0000
          description: |
            **Failure Details**
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}
  tag_release:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch